// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhx-aH9VbOdRh3SiD5iY5umKRY7TEFDXM',
    appId: '1:379239936131:web:ceef551bbe797121d3ebb6',
    messagingSenderId: '379239936131',
    projectId: 'electronic-shop-f9524',
    authDomain: 'electronic-shop-f9524.firebaseapp.com',
    storageBucket: 'electronic-shop-f9524.appspot.com',
    measurementId: 'G-WH1R9D8NHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsEddZDTYwCH1aO8_eJxONCkGsXIYozts',
    appId: '1:379239936131:android:d25bfaae2df6c7b1d3ebb6',
    messagingSenderId: '379239936131',
    projectId: 'electronic-shop-f9524',
    storageBucket: 'electronic-shop-f9524.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoTHRdoIcJ8JBDOvZ9plHF5W5qZjhYWYI',
    appId: '1:379239936131:ios:9f8c9784eee33f40d3ebb6',
    messagingSenderId: '379239936131',
    projectId: 'electronic-shop-f9524',
    storageBucket: 'electronic-shop-f9524.appspot.com',
    iosClientId: '379239936131-3n2o8q1jmjfib2vajl7ogphdvcm3a9f5.apps.googleusercontent.com',
    iosBundleId: 'com.example.electronicShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoTHRdoIcJ8JBDOvZ9plHF5W5qZjhYWYI',
    appId: '1:379239936131:ios:7a45f98ce9092e24d3ebb6',
    messagingSenderId: '379239936131',
    projectId: 'electronic-shop-f9524',
    storageBucket: 'electronic-shop-f9524.appspot.com',
    iosClientId: '379239936131-5b8ou3dbeihhkb382jfuvh2nrnrgb74b.apps.googleusercontent.com',
    iosBundleId: 'com.example.electronicShop.RunnerTests',
  );
}
